/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.appcelerator.timer;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="Timer", id="com.appcelerator.timer")
public class TimerModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TimerModule";
	private static final boolean DBG = TiConfig.LOGD;

	public TimerModule()
	{
		super();
	}

	// Methods

	/**
	 * return a microsecond timestamp
	 */
	@Kroll.method
	public long time()
	{
		return System.nanoTime() / 1000;
	}

}
